CurrencyRate.create(rate: 12000.00, finished_at: nil)
ProductCategory.create(name: "Кузов в сборе")
ProductCategory.create(name: "Кузов деталь")
ProductCategory.create(name: "Нелеквидит")
ProductCategory.create(name: "UMPT")
ProductCategory.create(name: "Импорт")
ProductCategory.create(name: "локал")
ProductCategory.create(name: "Корея", weight: 1)
Provider.create(name: "Клиент", weight: 1)
Provider.create(name: "UzAuto", weight: 0)
Buyer.create(name: "Клиент", weight: 1)
Storage.create(name: "global")
Storage.create(name: "GM")
Storage.create(name: "PARTS LINE")
User.create(name: 'Хусенов Азиз', role: 2, password: 'aziz_1001', email: 'aziz@gmail.com')
User.create(name: 'Раббимов Далер', role: 5, password: 'daler_1754', email: 'daler@gmail.com')
User.create(name: 'Мирзаев Журабек', role: 3, password: 'jorabek_5474', email: 'jorabek@gmail.com')
User.create(name: 'Рахимов Бобиршох',  role:	6, password: 'shokh_7984', email: 'shokh@gmail.com')
User.create(name: 'Суннат',	 role: 3, password: 'sunnat_2322', email: 'sunnat@gmail.com')
User.create(name: 'Пулатов Алишер',  role: 0, password: 'alisher_0546', email: 'alisher@gmail.com')
User.create(name: "Пулатов Улугбек",	 role: 0, password: 'bek_3565', email: 'ulugbek@gmail.com')
User.create(name: "Назаров Алижон",	 role: 1, password: 'alijon_9171', email: 'alijon@gmail.com')
