CurrencyRate.create(rate: 12000.00, finished_at: nil)
ProductCategory.create(name: "MAYKA")
ProductCategory.create(name: "OBUV")
ProductCategory.create(name: "KEPKI")
ProductCategory.create(name: "FUTBOLKI")
Provider.create(name: "Клиент", weight: 1)
Provider.create(name: "8Mart", weight: 0)
Buyer.create(name: "Клиент", weight: 1)
Storage.create(name: "global")
User.create(name: 'Суннат',	 role: 3, password: 'sunnat_2322', email: 'sunnat@gmail.com')
User.create(name: 'Пулатов Алишер',  role: 0, password: 'alisher_0546', email: 'alisher@gmail.com')
User.create(name: "Пулатов Улугбек",	 role: 0, password: 'bek_3565', email: 'ulugbek@gmail.com')
User.create(name: "Назаров Алижон",	 role: 1, password: 'alijon_9171', email: 'alijon@gmail.com')
