CurrencyRate.create(rate: 12400.00, finished_at: nil)
Provider.create(name: "Клиент", weight: 1)
Buyer.create(name: "Клиент", weight: 1)

Color.create(name: 'Белый', hex: '#FFFFFF')
Color.create(name: 'Чёрный', hex: '#000000')
Color.create(name: 'Коричневый', hex: '#A52A2A')
Color.create(name: 'Синий', hex: '#0000FF')
Color.create(name: 'Серый', hex: '#808080')
Color.create(name: 'Жёлтый', hex: '#FFFF00')
Color.create(name: 'Оранжевый', hex: '#FFA500')
Color.create(name: 'Фиолетовый', hex: '#800080')
Color.create(name: 'Розовый', hex: '#FFC0CB')
Color.create(name: 'Зелёный', hex: '#00FF00')
Color.create(name: 'Черпак', hex: '#008080')
Color.create(name: 'другой', hex: '#')
Color.create(name: 'прозрачный', hex: '#')
